server:
  port: 8089
spring:
  resources:
    static-locations: classpath:/templates/,classpath:/static/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/public/,classpath:/upload
  thymeleaf:
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true
#spring:
  application:
    name: microservice-consumer


eureka:
  client:
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:6001/eureka
  instance:
    instance-id: microservice-consumer-80
    prefer-ip-address: true     #访问路径可以显示IP地址

#注释后hystrix服务降级不可用
feign:
  httpclient:
    connection-timeout: 30000
    enabled: true




#分页配置
pagehelper:
  #  helperDialect: mysql  #方言  默认
  reasonable: true      #启动合理化
#  pageSizeZero: true    #小于pageIndex1时，pageIndex=1 默认

#默认支持文件上传:本示例上传七牛云
servlet:
  multipart:
    enabled: true
    max-file-size: 10000000      #单文件大小
    max-request-size: 100000000   #总大小
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000
#ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000