server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml
  type-aliases-package: com.cssl.pojo
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  application:
    #????
    name: microservice-hotel
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.107.103.69:3306/itrip?useUni code=true&characterEncoding=utf8
    username: root
    password: ailvxing@123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

  #???????
#  redis:
#    port: 6379
#    database: 0
#    host: 127.0.0.1
#    password:
#    timeout: 10s
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 5
#        min-idle: -1


eureka:
  client: #??????eureka?????
    service-url:
      #defaultZone: http://localhost:6001/eureka
      #Eureka?????
      defaultZone: http://localhost:6001/eureka/
  instance:
    instance-ie-d: microservicHotel8002
    prefer-ip-address: true     #????????IP??
    leaseRenewalIntervalInSeconds: 10   #???????????30??
    leaseExpirationDurationInSeconds: 30 #?????????90??

info:
  app.name: cssl-microservice
  company.name: www.cssl.com
  build.artifactId: microservice
  build.version: 1.0-SNAPSHOT


#spring:
#  boot:
#    admin:
#      client:
#        url: "http://localhost:8000"

#????
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#        - "*" # ??????health?info?metrics???actuator/+??????????????????health?info
#  endpoint:
#    health:
#      show-details: always #???actuator/health???????????{"status":"UP"}?status??????? DOWN??????????
